title: Resilience Bootcamp
description: Course hub for labs, slides, Kahootz, quizzes, and resilience resources.
url: "https://andry-collab.github.io"
baseurl: "/resilience-bootcamp"
theme: jekyll-theme-cayman
markdown: kramdown

